var color = "blue";
b = "purple";
console.log(color);
var namecheck1 = "blue";
console.log(namecheck1);
a = "purple";
console.log(a);
var namecheck = "Ahmed";
console.log(namecheck);
var namecheck4 = 46;
console.log(namecheck4);
var namecheck6 = "ahsan";
console.log(namecheck6);
